version: '3.9'

services:
  postgres:
    image: postgres:18
    container_name: realtymind_postgres
    restart: always
    environment:
      POSTGRES_USER: rm_user
      POSTGRES_PASSWORD: Ronaldo@1401
      POSTGRES_DB: realitymind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
